/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}", "./src/**/*.html"],
  theme: {
    extend: {
      colors: {
        od: {
          bg: '#2b2a27',
          'bg-darker': '#232220',
          'bg-darkest': '#1a1918',
          'bg-raised': '#33312e',
          'bg-hover': '#3b3936',
          'bg-active': '#44413d',
          'bg-input': '#1e1d1b',
          border: '#1e1d1b',
          'border-subtle': '#3b3936',
          'border-active': '#a3b18a',
          text: '#b8b5ad',
          'text-dim': '#7a7770',
          'text-muted': '#5c5954',
          'text-bright': '#d4d1c9',
          'text-white': '#edebe6',
          accent: '#a3b18a',
          'accent-bright': '#b5c49e',
          'accent-dim': '#8a9c72',
          'accent-bg': 'rgba(163, 177, 138, 0.1)',
          red: '#d4908a',
          'red-dim': '#b87872',
          'red-bg': '#2e2322',
          green: '#a3b18a',
          'green-dim': '#8a9c72',
          yellow: '#d4c196',
          'yellow-dim': '#bfaa7d',
          'yellow-bg': '#2e2b22',
          blue: '#8aafc4',
          'blue-dim': '#7299ad',
          'blue-bg': '#22282e',
          purple: '#b89cc4',
          'purple-dim': '#9e83ad',
          cyan: '#8abfb8',
          'cyan-dim': '#72a89f',
          orange: '#c4a88a',
        },
      },
      fontFamily: {
        mono: [
          'JetBrains Mono',
          'Fira Code',
          'SF Mono',
          'Cascadia Code',
          'monospace',
        ],
      },
      borderRadius: {
        od: '3px',
      },
      transitionDuration: {
        od: '120ms',
      },
      spacing: {
        'panel': '420px',
      },
    },
  },
  plugins: [],
};